---------------------------------------count
SELECT COUNT(1), department_id
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID is NOT NULL 
GROUP BY DEPARTMENT_ID 
HAVING COUNT(1)>1
ORDER BY DEPARTMENT_ID DESC 
---------------------------------------sum 
SELECT SUM(SALARY), DEPARTMENT_ID  
FROM DBO.S_HREMPLOYEES sh 
WHERE SALARY is NOT NULL 
GROUP BY DEPARTMENT_ID  
HAVING sum(SALARY)>10000
ORDER BY DEPARTMENT_ID  ASC  
--------------------------------------average
SELECT AVG(SALARY) ,DEPARTMENT_ID  
FROM DBO.S_HREMPLOYEES sh 
WHERE SALARY is NOT NULL 
GROUP BY DEPARTMENT_ID  
HAVING AVG(SALARY)>10000 
ORDER BY DEPARTMENT_ID ASC ;
--------------------------------------minimum
SELECT MIN(SALARY), DEPARTMENT_ID 
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID is NOT NULL 
GROUP BY DEPARTMENT_ID 
HAVING MIN(SALARY) <10000
ORDER BY DEPARTMENT_ID DESC;
--------------------------------------maximum
SELECT MAX(SALARY), DEPARTMENT_ID 
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID is NOT NULL 
GROUP BY DEPARTMENT_ID 
HAVING MAX(SALARY) >10000
ORDER BY DEPARTMENT_ID DESC;

select * from DBO.S_HREMPLOYEES;